robot_base_frame: base_perfect
transform_tolerance: 2.3
update_frequency: 0.5
publish_frequency: 0.5
global_frame: map
resolution: 1.0
rolling_window: false
track_unknown_space: true
footprint: [[0.1, 0.0], [0.0, 0.1], [-0.1, 0.0], [0.0, -0.1]]

plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: polygon_layer,    type: "polygon_layer::PolygonLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}
  - {name: sensor,           type: "costmap_2d::ObstacleLayer"}

static:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  subscribe_to_updates: true
  map_topic: /map

inflation:
  inflation_radius: 1.15

polygon_layer:
  resize_to_boundary: false

sensor:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan_base, inf_is_valid: true, raytrace_range: 25, obstacle_range: 25}
